"""Adding new attributes in the Goal module

Revision ID: 024cbcc0354d
Revises: e69f73b3a203
Create Date: 2025-03-19 18:42:37.261990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = '024cbcc0354d'
down_revision = 'e69f73b3a203'
branch_labels = None
depends_on = None

# Define the Enum type for 'priority'
priority_enum = ENUM('High', 'Medium', 'Low', name='priority', create_type=False)
status_enum = ENUM('Active', 'Completed', 'On Hold', 'Adjusted', name='goal_status', create_type=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('monthly_contribution', sa.Numeric(precision=12, scale=2), nullable=False, server_default='0'))
        # First, create the ENUM type in the database (if not created yet)
        op.execute("CREATE TYPE priority AS ENUM ('High', 'Medium', 'Low')")
        # Add the new column 'priority' with a default value
        op.add_column('goals', sa.Column('priority', priority_enum, nullable=False, server_default='Medium'))
        batch_op.add_column(sa.Column('expected_completion_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('funding_gap', sa.Numeric(precision=12, scale=2), nullable=True))
        # First, create the ENUM type in the database (if not created yet)
        op.execute("CREATE TYPE goal_status AS ENUM ('Active', 'Completed', 'On Hold', 'Adjusted')")
        # Add the new column 'status' with a default value
        op.add_column('goals', sa.Column('status', status_enum, nullable=False, server_default='Active'))
        batch_op.alter_column('current_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    """
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('current_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('funding_gap')
        batch_op.drop_column('expected_completion_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('monthly_contribution')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
