"""./run_migrations.sh

Revision ID: 1230e0d0be4b
Revises: 4c3219d557ed
Create Date: 2025-09-02 18:27:13.562671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1230e0d0be4b'
down_revision = '4c3219d557ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_categories', schema=None) as batch_op:
        batch_op.alter_column('category_type',
               existing_type=sa.UUID(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('transaction_categories_category_type_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories_type', ['category_type'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_categories_category_type_fkey'), 'categories_type', ['category_type'], ['type_id'])
        batch_op.alter_column('category_type',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###