"""updating the Education and Degrees models

Revision ID: 38d88416706f
Revises: 79ee48a6cf23
Create Date: 2025-07-15 22:35:24.529738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d88416706f'
down_revision = '79ee48a6cf23'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('education_level')

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
    """
    pass