"""goal allocation locking

Revision ID: 572ee6053716
Revises: 736cd90d9481
Create Date: 2025-10-07 08:28:05.912040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572ee6053716'
down_revision = '736cd90d9481'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['category_id'])

    with op.batch_alter_table('goal_priorities', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['priority_id'])

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['goal_id'])
        batch_op.create_foreign_key(None, 'goal_priorities', ['priority_id'], ['priority_id'])

    with op.batch_alter_table('monthly_goal_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_finalized', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deficit', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['allocation_id'])
        batch_op.create_foreign_key(None, 'goals', ['goal_id'], ['goal_id'])
        batch_op.drop_column('difference')
        batch_op.drop_column('actual_spent')

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_goal_allocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_spent', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('difference', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_deficit')
        batch_op.drop_column('is_finalized')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('goal_priorities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
    """
    pass