"""beneficiaries into fin records

Revision ID: 580bfbe0670a
Revises: ee16174d7b50
Create Date: 2025-11-20 13:38:09.201103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580bfbe0670a'
down_revision = 'ee16174d7b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_beneficiaries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_beneficiary_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'expense_beneficiaries', ['expense_beneficiary_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expense_beneficiary_id')

    with op.batch_alter_table('expense_beneficiaries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###