"""base_allocation_Rate

Revision ID: 5e86fe4e9aa0
Revises: 716129f56a57
Create Date: 2025-10-11 13:19:39.236627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e86fe4e9aa0'
down_revision = '716129f56a57'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_allocation_rate', sa.Numeric(precision=5, scale=4), nullable=True))

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.drop_column('base_allocation_rate')

    # ### end Alembic commands ###
    """
    pass