"""Added deficit and savings balance

Revision ID: 716129f56a57
Revises: 572ee6053716
Create Date: 2025-10-11 12:39:10.913829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716129f56a57'
down_revision = '572ee6053716'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deficit_balance', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('savings_balance', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.drop_column('savings_balance')
        batch_op.drop_column('deficit_balance')

    # ### end Alembic commands ###
    """
    pass