"""updated the goal categories

Revision ID: 736cd90d9481
Revises: fb5c2c39d2ec
Create Date: 2025-10-04 15:01:53.259519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736cd90d9481'
down_revision = 'fb5c2c39d2ec'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['category_id'])

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.alter_column('current_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.create_foreign_key(None, 'goal_categories', ['category'], ['category_id'])

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('current_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('goal_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###  
    """
    pass