"""updating by making the education and degrees common and dynamic

Revision ID: 79ee48a6cf23
Revises: 89c128448dc9
Create Date: 2025-07-15 22:07:36.062904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ee48a6cf23'
down_revision = '89c128448dc9'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['type_id'])

    with op.batch_alter_table('degrees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['degree_id'])

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree_id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['education_id'])
        batch_op.create_foreign_key(None, 'degrees', ['degree_id'], ['degree_id'])
        batch_op.drop_column('degree')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['goal_id'])

    with op.batch_alter_table('transaction_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['category_id'])

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('degree_id')

    with op.batch_alter_table('degrees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('categories_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
    """
    pass