"""Added employment status to users   model

Revision ID: 8ac248aa7981
Revises: 06556e54e125
Create Date: 2025-07-23 08:37:55.495128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac248aa7981'
down_revision = '06556e54e125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_statuses',
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('status_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('status_id'),
    sa.UniqueConstraint('status_name')
    )
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['record_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_employed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('employment_status', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'employment_statuses', ['employment_status'], ['status_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employment_status')
        batch_op.drop_column('is_employed')

    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('employment_statuses')
    # ### end Alembic commands ###
