"""last updated at

Revision ID: 9e9d73b7d872
Revises: b58270750a49
Create Date: 2025-10-13 21:44:23.609510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9d73b7d872'
down_revision = 'b58270750a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_calculated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('actual_monthly_expenses')
        batch_op.drop_column('actual_monthly_income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_monthly_income', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('actual_monthly_expenses', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('last_calculated_at')

    # ### end Alembic commands ###