"""profile allocations

Revision ID: a16ae28e564e
Revises: d32b46ff68d4
Create Date: 2025-10-24 21:21:31.818344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16ae28e564e'
down_revision = 'd32b46ff68d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protection_level', sa.Enum('FLEXIBLE', 'PROTECTED', 'FINALIZED', name='goalprotectionlevel'), nullable=False, server_default='FLEXIBLE'))
        batch_op.add_column(sa.Column('protection_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('protected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('is_essential', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_committed_expense', sa.Boolean(), nullable=False, server_default='false'))

    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_savings_in_alloc', sa.Boolean(), nullable=True, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.drop_column('include_savings_in_alloc')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('is_committed_expense')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_essential')
        batch_op.drop_column('is_locked')
        batch_op.drop_column('protected_at')
        batch_op.drop_column('protection_reason')
        batch_op.drop_column('protection_level')

    # ### end Alembic commands ###