"""updated the financial profile model

Revision ID: b58270750a49
Revises: 5e86fe4e9aa0
Create Date: 2025-10-13 21:41:22.878615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58270750a49'
down_revision = '5e86fe4e9aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_expense_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_income_snapshot', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_financial_profiles', schema=None) as batch_op:
        batch_op.drop_column('total_income_snapshot')
        batch_op.drop_column('total_expense_snapshot')

    # ### end Alembic commands ###