"""goal improved

Revision ID: cc2d6994a63c
Revises: 9e9d73b7d872
Create Date: 2025-10-17 08:27:56.151814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2d6994a63c'
down_revision = '9e9d73b7d872'
branch_labels = None
depends_on = None


def upgrade():
    """
    
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protection_level', sa.Enum('FLEXIBLE', 'PROTECTED', 'FINALIZED', name='goalprotectionlevel'), nullable=False))

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('protection_level')

    # ### end Alembic commands ###
    """
    pass