"""goal protection and flexibility

Revision ID: d32b46ff68d4
Revises: cc2d6994a63c
Create Date: 2025-10-17 08:46:11.654470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32b46ff68d4'
down_revision = 'cc2d6994a63c'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protection_level', sa.Enum('FLEXIBLE', 'PROTECTED', 'FINALIZED', name='goalprotectionlevel'), nullable=False))
        batch_op.add_column(sa.Column('protection_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('protected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_essential', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_committed_expense', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###
    """
    pass
def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('is_committed_expense')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_essential')
        batch_op.drop_column('is_locked')
        batch_op.drop_column('protected_at')
        batch_op.drop_column('protection_reason')
        batch_op.drop_column('protection_level')

    # ### end Alembic commands ###
    """
    pass