"""slug removed

Revision ID: d71808be851b
Revises: 7813254e9639
Create Date: 2025-11-18 00:21:22.711861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71808be851b'
down_revision = '7813254e9639'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_orientations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expense_orientations_slug_key'), type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_orientations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('expense_orientations_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
    """
    pass