"""financial records udpated to flag a record

Revision ID: d7362fda0a22
Revises: a16ae28e564e
Create Date: 2025-10-24 23:08:26.494071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7362fda0a22'
down_revision = 'a16ae28e564e'
branch_labels = None
depends_on = None


def upgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allocation_transaction', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###
    """
    pass

def downgrade():
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_column('is_allocation_transaction')

    # ### end Alembic commands ###
    """
    pass