"""Update the financial records table to include the expense allocations"

Revision ID: ee16174d7b50
Revises: d71808be851b
Create Date: 2025-11-18 00:30:42.224739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee16174d7b50'
down_revision = 'd71808be851b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_orientation_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'expense_orientations', ['expense_orientation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('expense_orientation_id')

    # ### end Alembic commands ###