"""examples to transaction categories

Revision ID: fee82014e28f
Revises: 580bfbe0670a
Create Date: 2025-11-22 16:38:59.927880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fee82014e28f'
down_revision = '580bfbe0670a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_categories', schema=None) as batch_op:
        batch_op.drop_column('examples')

    # ### end Alembic commands ###